[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
basesepolia = "${RPC_BASE}"

[etherscan]
basesepolia = { key = "${BASESCAN_KEY}" }

[fmt]
line_length = 100

[soldeer]
recursive_deps = true
remappings_version = false

[dependencies]
forge-std = "1.9.6"
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
"@openzeppelin-contracts" = "5.3.0"
eth-infinitism-account-abstraction = "0.8.0"
