[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
basesepolia = "${RPC_BASE}"

[etherscan]
basesepolia = { key = "${BASESCAN_KEY}" }

[fmt]
line_length = 100
