[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
test = "test"
script = "script"
cache_path = "cache"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
ffi = false
fs_permissions = [{access = "read-write", path = "./"}]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[rpc_endpoints]
basesepolia = "${RPC_URL_BASE_SEPOLIA}"
basemainnet = "${RPC_URL_BASE_MAINNET}"
local = "http://localhost:8545"

[etherscan]
basesepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
basemainnet = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

[fmt]
line_length = 100

[soldeer]
recursive_deps = true
remappings_version = false

[dependencies]
forge-std = "1.9.6"
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
"@openzeppelin-contracts" = "5.3.0"
eth-infinitism-account-abstraction = "0.8.0"
